version: '3.8'
services:
    web:
        build: .
        volumes:
            - ./AloaiApi:/app
            - ./AloaiAPi/entrypoint.sh:/entrypoint.sh
        ports:
            - '8000:5000'
        depends_on:
            - db
    db:
        image: 'mcr.microsoft.com/mssql/server'
        environment:
            SA_PASSWORD: 'Your_password123'
            ACCEPT_EULA: 'Y'
